version: "3.7"

services:
  lima-mysql:
    container_name: lima-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lima-limon
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306
    networks:
      - lima-network

  lima-limon:
    container_name: lima-limon
    image: lima-limon:latest
    build:
      context: ./lima-limon
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    depends_on:
      - lima-mysql
    networks:
      lima-network:
        aliases:
          - alias-lima-limon

  nginx-server:
    container_name: nginx-server
    image: nginx:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - lima-limon
    networks:
      - lima-network

networks:
  lima-network:
    driver: bridge
